# Generated by Django 3.1.4 on 2021-03-08 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='DateWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('AQI', models.IntegerField(blank=True)),
                ('state', models.TextField()),
                ('date', models.DateField()),
                ('update_date', models.DateField(auto_now=True)),
                ('max_temperature', models.FloatField()),
                ('mini_temperature', models.FloatField()),
                ('wind_power', models.FloatField(blank=True, default=0.0)),
                ('wind_direction', models.TextField(blank=True)),
                ('city', models.CharField(max_length=40)),
                ('extend_detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'DateWeather',
            },
        ),
        migrations.CreateModel(
            name='WeatherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('wind_power', models.FloatField(blank=True, default=0.0)),
                ('wind_direction', models.TextField(blank=True)),
                ('precipitation', models.IntegerField()),
                ('relative_humidity', models.IntegerField()),
                ('AQI', models.IntegerField(blank=True)),
                ('Weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DateWeather', to='weather_show_app.dateweather')),
            ],
            options={
                'db_table': 'WeatherDetail',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ManyToManyField(related_name='City', to='weather_show_app.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favourite',
            },
        ),
    ]
