# Generated by Django 3.1.4 on 2021-03-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateweather',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='weather_show_app.city'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='city',
            field=models.ManyToManyField(related_name='fav_city', to='weather_show_app.City'),
        ),
    ]
