# Generated by Django 3.1.4 on 2021-03-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0002_auto_20210309_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateweather',
            old_name='mini_temperature',
            new_name='min_temperature',
        ),
    ]
