# Generated by Django 3.1.4 on 2021-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0004_auto_20210310_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateweather',
            name='AQI',
        ),
        migrations.RemoveField(
            model_name='dateweather',
            name='extend_detail',
        ),
        migrations.AlterField(
            model_name='weatherdetail',
            name='AQI',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
