# Generated by Django 3.1.4 on 2021-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0005_auto_20210306_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='extend_detail',
            field=models.TextField(blank=True),
        ),
    ]
