# Generated by Django 3.1.4 on 2021-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0006_auto_20210310_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateweather',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
