# Generated by Django 3.1.4 on 2021-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0007_auto_20210310_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateweather',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dateweather',
            unique_together={('date', 'city')},
        ),
    ]
