# Generated by Django 3.1.4 on 2021-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0008_auto_20210310_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdetail',
            name='precipitation',
            field=models.FloatField(),
        ),
    ]
