# Generated by Django 3.1.4 on 2021-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0009_auto_20210310_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateweather',
            name='dressing_index',
            field=models.TextField(default=''),
        ),
    ]
