# Generated by Django 3.1.4 on 2021-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0011_auto_20210325_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdetail',
            name='dressing_index',
        ),
        migrations.AddField(
            model_name='dateweather',
            name='dressing_index',
            field=models.TextField(default=''),
        ),
    ]
