# Generated by Django 3.1.4 on 2021-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0013_dateweather_dressing_index_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateweather',
            name='dressing_index',
            field=models.CharField(default='', max_length=50),
        ),
    ]
