# Generated by Django 3.1.4 on 2021-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0014_auto_20210326_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='direct_city_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='is_city',
            field=models.BooleanField(default=False),
        ),
    ]
