# Generated by Django 3.1.4 on 2021-03-29 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0016_auto_20210328_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdetail',
            name='belong_to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
