# Generated by Django 3.1.4 on 2021-03-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0017_weatherdetail_belong_to_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherDetail',
            new_name='HourWeather',
        ),
        migrations.AlterModelTable(
            name='hourweather',
            table='HourWeather',
        ),
    ]
