# Generated by Django 3.1.4 on 2021-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='weather',
            table='Weather',
        ),
        migrations.AlterModelTable(
            name='wind',
            table='Wind',
        ),
    ]
