# Generated by Django 3.1.4 on 2021-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0002_auto_20210302_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_pinyin',
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
