# Generated by Django 3.1.4 on 2021-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_show_app', '0003_auto_20210303_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='AQI',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
